title: Haoran Zhang
description: MS Computer Science @ University of Southern California
site_title: 'Haoran'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Ricardoran
# blog_url: https://www.nagekar.com
email: ricardo15222024@gmail.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/photo.jpg

# Google Analytics ID
# google_analytics: 